project:
  type: website
  output-dir: docs
  
website:
  title: "BIOL806 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/camille-kroot/BIOL806Website.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 20235, Camille Kroot"

format:
  html:
    theme: cerulean
    toc: true

editor: source

